#@ load("@ytt:data", "data")
#@ load("helpers.star", "labels_for_kservice", "image_for_component")
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend
  namespace: #@ data.values.NAMESPACE
  labels: #@ labels_for_kservice("frontend")
spec:
  template:
    spec:
      containers:
      - name: frontend
        image: #@ image_for_component("frontend")
        resources:
          requests:
            memory: 256M
          limits:
            memory: 256M
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: backend
  namespace: #@ data.values.NAMESPACE
  labels: #@ labels_for_kservice("backend")
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scaleDownDelay: #@ "1m" if data.values.USE_NATIVE_BACKEND else "3m"
    spec:
      containers:
      - name: backend
        image: #@ image_for_component("backend-native" if data.values.USE_NATIVE_BACKEND else "backend")
        resources:
          requests:
            memory: #@ "256M" if data.values.USE_NATIVE_BACKEND else "1G"
          limits:
            memory: #@ "256M" if data.values.USE_NATIVE_BACKEND else "1G"
        env:
        - name: SPRING_CONFIG_IMPORT
          value: configtree:/etc/config/*/
        volumeMounts:
        - mountPath: /etc/config/db
          name: db
        #! Load secrets generated by the Tanzu SQL operator.
        - mountPath: /etc/config/db-secret/spring.datasource.password
          name: db-secret
          subPath: password
      volumes:
      - name: db
        secret:
          secretName: db
      - name: db-secret
        secret:
          secretName: pgdb-db-secret
