#@data/values
---
#! Set application name.
APP: kn-todo

#! Set target namespace.
NAMESPACE: kn-todo

#! Set image repository where to find container images.
IMAGE_REPOSITORY: index.docker.io/alexandreroman

#! Set the public-facing domain used for accessing the application.
DOMAIN: kn-todo.example.com

#! Set cert-manager cluster issuer to use when ingress TLS is enabled.
CERT_MANAGER_CLUSTER_ISSUER: letsencrypt-prod

#! Set database name.
DATABASE_NAME: pgdb

#! Set to true to use a native-image for the backend component.
USE_NATIVE_BACKEND: false

#! Set the max number of instances for each component.
BACKEND_SCALING_MAX: 1
FRONTEND_SCALING_MAX: 1

#! Set the target request per second for each component.
BACKEND_RPS_MAX: 50
FRONTEND_RPS_MAX: 200

#! Set tag for container images.
IMAGES:
  frontend: latest
  backend: latest
  backend-native: latest
