#@data/values
---
#! Set application name.
APP: kn-todo

#! Set target namespace.
NAMESPACE: kn-todo

#! Set image repository where to find container images.
IMAGE_REPOSITORY: index.docker.io/alexandreroman

#! Set the public-facing domain used for accessing the application.
DOMAIN: kn-todo.example.com

#! Set database name.
DATABASE_NAME: pgdb

#! Set to true to use a native-image for the backend component.
USE_NATIVE_BACKEND: false

#! Set tag for container images.
IMAGES:
  frontend: latest
  backend: latest
  backend-native: latest
